"""ReceiptStore — Persistent + in-memory DawsOS-style receipts.

Writes human-readable receipts to disk under receipts/ (markdown) 
and optionally to SQLite for state that survives uvicorn restarts.
This upgrade was executed per the Mac Studio backend lock-in receipt.
"""

from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime
import sqlite3
import json


class ReceiptStore:
    def __init__(self, base_dir: Path = Path("receipts"), db_path: Optional[Path] = None):
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self.memory: List[Dict[str, Any]] = []
        self.db_path = db_path
        self.conn = None
        if db_path:
            self._init_sqlite(db_path)

    def _init_sqlite(self, db_path: Path):
        self.conn = sqlite3.connect(str(db_path), check_same_thread=False)
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS receipts (
                id TEXT PRIMARY KEY,
                turn INTEGER,
                action TEXT,
                status TEXT,
                fun_score REAL,
                payload TEXT,
                created_at TEXT
            )
        """)
        self.conn.execute("""
            CREATE TABLE IF NOT EXISTS state_snapshots (
                key TEXT PRIMARY KEY,
                value TEXT,
                updated_at TEXT
            )
        """)
        self.conn.commit()
        # Load recent receipts from DB into memory
        cur = self.conn.execute("SELECT payload FROM receipts ORDER BY turn DESC, created_at DESC LIMIT 50")
        for (payload,) in cur.fetchall():
            try:
                self.memory.append(json.loads(payload))
            except Exception:
                pass
        self.memory.reverse()  # oldest first

    def append(self, receipt: Dict[str, Any], filename_hint: str = "governance") -> Path:
        self.memory.append(receipt)

        # Always write human-readable markdown
        ts = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
        fname = f"{filename_hint}-{ts}.md"
        path = self.base_dir / fname

        lines = [
            f"# Receipt {receipt.get('id', receipt.get('turn', 'unknown'))}",
            f"**Turn/Cycle**: {receipt.get('turn')}",
            f"**Action**: {receipt.get('action', receipt.get('status'))}",
            f"**Status**: {receipt.get('status')}",
            f"**Fun/Quality Score**: {receipt.get('fun_score')}",
            "",
            "## Details",
        ]
        for k, v in receipt.items():
            if k not in ("id", "turn", "action", "status", "fun_score"):
                lines.append(f"- **{k}**: {v}")
        lines.append("")
        lines.append(f"_Generated by CivForge core at {datetime.utcnow().isoformat()}_")
        path.write_text("\n".join(lines))

        # Optional SQLite persistence
        if self.conn:
            try:
                rid = receipt.get("id") or f"r-{receipt.get('turn', 0)}-{ts}"
                self.conn.execute(
                    "INSERT OR REPLACE INTO receipts (id, turn, action, status, fun_score, payload, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        rid,
                        receipt.get("turn", 0),
                        receipt.get("action", receipt.get("status")),
                        receipt.get("status"),
                        float(receipt.get("fun_score", 0) or 0),
                        json.dumps(receipt),
                        datetime.utcnow().isoformat(),
                    ),
                )
                self.conn.commit()
            except Exception as e:
                print(f"[ReceiptStore] SQLite append warning: {e}")

        return path

    def recent(self, n: int = 10) -> List[Dict[str, Any]]:
        return self.memory[-n:]

    def save_state(self, key: str, value: Dict[str, Any]):
        if not self.conn:
            return
        try:
            self.conn.execute(
                "INSERT OR REPLACE INTO state_snapshots (key, value, updated_at) VALUES (?, ?, ?)",
                (key, json.dumps(value), datetime.utcnow().isoformat()),
            )
            self.conn.commit()
        except Exception as e:
            print(f"[ReceiptStore] save_state warning: {e}")

    def load_state(self, key: str) -> Optional[Dict[str, Any]]:
        if not self.conn:
            return None
        try:
            cur = self.conn.execute("SELECT value FROM state_snapshots WHERE key = ?", (key,))
            row = cur.fetchone()
            if row:
                return json.loads(row[0])
        except Exception:
            pass
        return None

    def close(self):
        if self.conn:
            self.conn.close()

